# Generated by Django 2.1.5 on 2023-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolnews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.RemoveField(
            model_name='page',
            name='views',
        ),
        migrations.AddField(
            model_name='page',
            name='author',
            field=models.TextField(default='johndoe', max_length=128),
        ),
        migrations.AddField(
            model_name='page',
            name='date',
            field=models.DateField(max_length=0, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='text',
            field=models.TextField(default='This is example text', max_length=1024),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.TextField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
